version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mch_db
      - POSTGRES_USER=mch_user
      - POSTGRES_PASSWORD=mch_pass

  web:
    build: ./backend
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=mch_db
      - POSTGRES_USER=mch_user
      - POSTGRES_PASSWORD=mch_pass
    depends_on:
      - db

volumes:
  postgres_data:
