# Generated by Django 6.0.5 on 2026-05-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ANCVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateField()),
                ("weight", models.FloatField(help_text="Weight in kg")),
                ("bp_systolic", models.IntegerField()),
                ("bp_diastolic", models.IntegerField()),
                ("fundal_height", models.FloatField(blank=True, null=True)),
                ("fetal_heart_rate", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("ANC", "Antenatal Care"),
                            ("PNC", "Postnatal Care"),
                            ("VACCINATION", "Vaccination"),
                            ("GENERAL", "General Checkup"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("MISSED", "Missed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
