# Generated by Django 6.0.5 on 2026-05-26 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ancvisit",
            name="pregnancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anc_visits",
                to="patients.pregnancy",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="child",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.child",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="health_worker",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["NURSE", "DOCTOR", "CHW"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.mother",
            ),
        ),
    ]
